site_name: Live de Python
theme: readthedocs

# nav:
#   - Home: index.md
#   - Sobre: sobre.md
#   - Contribuições:
#       - Eventos: contribuir/eventos.md
#       - Traduções: contribuir/traducao.md

extra_css:
  - css/extra_css.css